### ISSUE TITLE
[Feature request] Add info about version in "about"

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/firstrunwizard#545] opened 2020-09-17 16:51 UTC
It would be great to add info about version in "about" (Main menu - > About).
All desktop apps contains info about app version and sometimes info about components versions in "about" window.
Maybe nextcloud should contain one page with informations about nextcloud's version and versions of all apps and modules (php version etc.).

"About" could contains info about nextcloud's version and link to page with other informations. I mean just info about versions, not option to update apps etc.

**Comment by juliushaertl** [comment] 2021-06-15 10:18
Duplicate of https://github.com/nextcloud/firstrunwizard/issues/82

**Closed by juliushaertl** 2021-06-15 10:18 UTC
