### ISSUE TITLE
Rethink linking to Riot for an IRC channel

### ISSUE THREAD

**Issue by aaronraimist** [nextcloud/firstrunwizard#87] opened 2018-11-12 05:01 UTC
I think you need to rethink linking to Riot here https://github.com/nextcloud/firstrunwizard/commit/5ee3a094a166b523058aca17ed8f6ece19cef926. 

I'm coming from the Matrix community and don't know much about Nextcloud but we keep getting people in random Matrix rooms looking for Nextcloud support. I guess this is because when people click that link, they create an account and then Riot doesn't bring them back to the room they clicked on before they registered so it just presents them a list of other rooms they can join.

Yes Riot could probably improve it's onboarding experience to make this use case a little better but I would HIGHLY encourage you to link to both an IRC web chat and then if someone is already a Matrix user they can click a link to be taken to Matrix (probably though a link more like https://matrix.to/#/#freenode_#nextcloud:matrix.org instead of just linking straight to Riot).

As a hardcore matrix user, I totally agree with the points made here
https://github.com/nextcloud/firstrunwizard/pull/68#issuecomment-393509132.

-----
@ara4n thoughts? See the conversation I just had here: https://matrix.to/#/!HsxjoYRFsDtWBgDQPh:matrix.org/$1541996545947372yofRa:matrix.org?via=matrix.org&via=chat.weho.st&via=disroot.org&via=riot.tenx.tech

This guy spent a ton of time trying to setup an account for Matrix and ended up with a really bad experience (chat continued into a private room). I've seen several people with similar experiences in #matrix:matrix.org and other rooms looking for Nextcloud support like this.

**Comment by aaronraimist** [comment] 2018-11-12 05:05
Just for my own memory the page with this link looks like this:
![screen shot 2018-11-11 at 11 05 13 pm](https://user-images.githubusercontent.com/5855073/48327786-4369ce80-e606-11e8-952e-550005766b5d.png)

**Comment by MorrisJobke** [comment] 2018-11-12 11:02
cc @jancborchardt because you changed it here.

cc @nextcloud/designers for the UX

**Comment by juliushaertl** [comment] 2018-11-12 17:41
Seems like there have been some changes on the matrix side, since this is now defenitely not easy to use anymore. I remeber it was basically one click in the past to join a room as a guest. I'm fine to go back to the freenode webchat for now.

**Comment by jancborchardt** [comment] 2018-11-12 20:36
> I guess this is because when people click that link, they create an account and then Riot doesn't bring them back to the room they clicked on before they registered so it just presents them a list of other rooms they can join.
> Yes Riot could probably improve it's onboarding experience to make this use case a little better

Yes, absolutely. This is something to be fixed on Riot’s side.


> but I would HIGHLY encourage you to link to both an IRC web chat and then if someone is already a Matrix user they can click a link to be taken to Matrix (probably though a link more like https://matrix.to/#/#freenode_#nextcloud:matrix.org instead of just linking straight to Riot).

Sorry but this is just too convoluted for anyone but programmers. This matrix.to page looks horrible. :\ We want to make this accessible to normal people, and IRC webchat is a huge step down.

**Comment by aaronraimist** [comment] 2018-11-12 20:49
Yes sure but I'm just telling you that right now, you are losing some number of people that are looking for Nextcloud support and aren't finding it.

**Comment by ara4n** [comment] 2018-11-12 23:41
> We should stick with Riot, and this issue should be fixed in Riot. We can’t be the only ones having this issue?

this looks like a big regression on the Riot side - we will prioritise a fix asap. please don’t go back to an irc webclient!

cc @lampholder - i suspect this is yet more ILAG+GDPR fallout?

**Comment by lampholder** [comment] 2018-11-13 16:03
This'll be a side effect of the GDRP work, and the fix should already be nearing completion. I'll check on the status and report the details here.

**Comment by jancborchardt** [comment] 2018-11-20 15:16
Thank you so much! :) We love Riot and want to continue using and advocating it!

**Comment by lampholder** [comment] 2018-12-21 10:02
We've now deployed the change to the matrix.org homeserver, the web application (https://riot.im/app) and the mobile apps 😁 

Accepting the server's terms and conditions is now part of registration proper, so it no longer breaks the flow of new users joining rooms.

Please let me know if you have any questions!

**Comment by jancborchardt** [comment] 2018-12-21 13:39
Great great stuff, thank you so much! :slightly_smiling_face: :tada:

I guess some of you Riot folks will be at FOSDEM (or CCC)? Come by the Nextcloud booth and let’s have a chat! (Or we come to you if you have a booth! :)

**Closed by jancborchardt** 2018-12-21 13:39 UTC
Labels: 1. to develop

**Comment by lampholder** [comment] 2018-12-21 13:51
We're a both! We have a stand and a main-track talk at FOSDEM - see you there!
